name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: littleTT0704/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          output_action: gist
          committer_gist: dad350878defbdbb6570a113e39fa396
          
          # Options
          base_indepth: yes
          repositories_affiliations: owner, collaborator, organization_member
          commits_authoring: Jiatai Li, littleTT0704, littlett0704@gmail.com, jiatail@andrew.cmu.edu
          user: littleTT0704
          template: classic
          base: header, activity, community, repositories, metadata
          config_display: large
          config_octicon: yes
          config_timezone: America/New_York
          config_twemoji: yes
          plugin_calendar: yes
          plugin_calendar_limit: 2
          plugin_followup: yes
          plugin_followup_sections: user, repositories
          plugin_followup_indepth: yes
          plugin_habits: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 30
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_habits_languages_limit: 6
          plugin_habits_languages_threshold: 0%
          plugin_languages: yes
          plugin_languages_ignored: html
          plugin_languages_colors: github
          plugin_languages_sections: most-used
          plugin_languages_details: bytes-size, percentage, lines
          plugin_languages_indepth: yes
          plugin_languages_analysis_timeout: 60
          plugin_languages_analysis_timeout_repositories: 15
          plugin_languages_categories: programming
          plugin_rss: yes
          plugin_rss_limit: 4
          plugin_rss_source: https://blog.littlett.top/atom.xml
